name: bgc-ocean-ml
channels:
  - pytorch
  - conda-forge
dependencies:
  # Core ML (CPU-only build, will use system CUDA via module)
  - pytorch>=2.2
  - torchvision
  - torchaudio

  # Data handling
  - xarray
  - netcdf4
  - dask
  - zarr

  # Utilities
  - numpy
  - pandas
  - scipy
  - tqdm
  - pyyaml
  - json5

  # Plotting & viz
  - matplotlib
  - plotly

  # Metrics / analysis
  - scikit-learn

  # HPC & config
  - hydra-core
  - omegaconf

  # Jupyter / Notebooks
  - jupyter
  - notebook
  - ipykernel
